<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="theme-color" content="#164f3d">
        <title>Dashboard | Barangay Information System</title>
        @fonts
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    </head>
    <body class="workspace-page">
        <a class="skip-link" href="#workspace-main">Skip to content</a>
        <button class="sidebar-backdrop" aria-label="Close navigation" type="button" hidden></button>
        <aside class="workspace-sidebar" id="workspace-navigation" aria-label="Workspace navigation">
            <a href="{{ route('home') }}" class="brand workspace-brand"><span class="brand-mark"><i data-lucide="landmark" aria-hidden="true"></i></span><span class="brand-name">Barangay<span>INFORMATION SYSTEM</span></span></a>
            <div class="workspace-label">STAFF WORKSPACE <span>DEMO</span></div>
            <nav class="workspace-nav" aria-label="Main workspace">
                <a href="#overview" data-section="overview" class="selected" aria-current="page"><i data-lucide="layout-dashboard" aria-hidden="true"></i> Overview</a>
                <span class="nav-group-label">BARANGAY MANAGEMENT</span>
                <a href="#residents" data-section="residents"><i data-lucide="users-round" aria-hidden="true"></i> Residents</a>
                <a href="#households" data-section="households"><i data-lucide="house" aria-hidden="true"></i> Households</a>
                <a href="#certificates" data-section="certificates"><i data-lucide="files" aria-hidden="true"></i> Certificates <span class="nav-count">6</span></a>
                <a href="#blotter" data-section="blotter"><i data-lucide="notebook-pen" aria-hidden="true"></i> Blotter records</a>
                <a href="#officials" data-section="officials"><i data-lucide="badge-check" aria-hidden="true"></i> Barangay officials</a>
                <span class="nav-group-label">INSIGHTS</span>
                <a href="#reports" data-section="reports"><i data-lucide="chart-no-axes-combined" aria-hidden="true"></i> Reports & analytics</a>
            </nav>
            <div class="sidebar-bottom">
                <a class="public-site-link" href="{{ route('home') }}"><i data-lucide="globe" aria-hidden="true"></i> Public website <i data-lucide="arrow-up-right" aria-hidden="true"></i></a>
                <div class="sidebar-profile"><span class="staff-avatar">BS</span><span><strong>Barangay staff</strong><small>Demo session</small></span><form method="POST" action="{{ route('logout') }}">@csrf<button class="signout-button" title="Sign out" aria-label="Sign out" type="submit"><i data-lucide="log-out" aria-hidden="true"></i></button></form></div>
            </div>
        </aside>
        <div class="workspace-shell">
            <header class="workspace-topbar">
                <div class="workspace-breadcrumb"><button type="button" class="icon-button sidebar-toggle" aria-label="Open sidebar" aria-controls="workspace-navigation" aria-expanded="false" title="Open sidebar"><i data-lucide="panel-left" aria-hidden="true"></i></button><span>Workspace</span><i data-lucide="chevron-right" aria-hidden="true"></i><strong id="breadcrumb-current">Overview</strong></div>
                <div class="topbar-actions"><span class="demo-tag"><span></span> Sample data</span><span class="topbar-divider"></span><button type="button" class="notification-button" aria-label="View notifications" title="Notifications" data-workspace-detail="notifications"><i data-lucide="bell" aria-hidden="true"></i><span></span></button><span class="topbar-avatar" aria-label="Barangay staff">BS</span></div>
            </header>
            <main class="workspace-main" id="workspace-main">
                <div class="workspace-heading"><div><div class="eyebrow">BARANGAY INFORMATION SYSTEM</div><h1 id="workspace-title">Dashboard</h1><p id="workspace-subtitle">Welcome back. Here's what's happening in your barangay.</p></div><div class="workspace-heading-actions"><span class="workspace-date"><i data-lucide="calendar-days" aria-hidden="true"></i> {{ now()->format('M d, Y') }}</span><button type="button" class="button button-primary" data-new-resident><i data-lucide="plus" aria-hidden="true"></i> Add resident</button></div></div>

                <div id="overview-view">
                    <div class="workspace-stats">
                        @foreach ([
                            ['label' => 'Total residents', 'value' => '1,248', 'icon' => 'users-round', 'tone' => 'green', 'note' => '+24 this month', 'sub' => 'Registered residents', 'section' => 'residents'],
                            ['label' => 'Households', 'value' => '326', 'icon' => 'house', 'tone' => 'blue', 'note' => 'Across 6 puroks', 'sub' => 'Active households', 'section' => 'households'],
                            ['label' => 'Certificates issued', 'value' => '48', 'icon' => 'file-check-2', 'tone' => 'gold', 'note' => '6 awaiting review', 'sub' => 'This month', 'section' => 'certificates'],
                            ['label' => 'Open blotter cases', 'value' => '4', 'icon' => 'notebook-pen', 'tone' => 'rose', 'note' => '2 scheduled hearings', 'sub' => 'For follow-up', 'section' => 'blotter'],
                        ] as $stat)
                            <a class="stat-tile" href="#{{ $stat['section'] }}"><div class="stat-top"><span>{{ $stat['label'] }}</span><span class="stat-icon {{ $stat['tone'] }}"><i data-lucide="{{ $stat['icon'] }}" aria-hidden="true"></i></span></div><strong class="stat-value" @if ($stat['section'] === 'residents') id="resident-count" @endif>{{ $stat['value'] }}</strong><span class="stat-subtitle">{{ $stat['sub'] }}</span><div class="stat-bottom"><span class="{{ $stat['tone'] }}">{{ $stat['note'] }}</span><i data-lucide="arrow-up-right" aria-hidden="true"></i></div></a>
                        @endforeach
                    </div>
                    <div class="workspace-analytics">
                        <section class="activity-chart" aria-labelledby="chart-heading">
                            <div class="workspace-section-heading"><div><h2 id="chart-heading">Certificate activity</h2><p>Issued documents over the past six months</p></div><label class="period-select"><span class="sr-only">Chart period</span><select id="chart-period"><option value="recent">Apr - Sep 2026</option><option value="previous">Oct 2025 - Mar 2026</option></select><i data-lucide="chevron-down" aria-hidden="true"></i></label></div>
                            <div class="chart-summary"><strong id="chart-total">242</strong><span>certificates issued</span><span class="chart-trend" id="chart-trend"><i data-lucide="trending-up" aria-hidden="true"></i> +14% vs. previous period</span></div>
                            <div class="bar-chart" id="certificate-chart" role="img" aria-label="Monthly certificates issued: April 30, May 36, June 41, July 39, August 48, September 48."><div class="chart-axis"><span>60</span><span>40</span><span>20</span><span>0</span></div><div class="chart-plot" id="chart-bars"></div></div>
                        </section>
                        <section class="population-section" aria-labelledby="population-heading"><div class="workspace-section-heading"><div><h2 id="population-heading">Community at a glance</h2><p>Registered resident demographics</p></div><i data-lucide="users-round" aria-hidden="true"></i></div><div class="population-content"><div class="population-donut" role="img" aria-label="Female residents: 652, 52.2 percent. Male residents: 596, 47.8 percent."><div><strong>1,248</strong><span>residents</span></div></div><div class="population-legend"><div><span class="legend-dot female"></span><span>Female<strong>652 <small>52.2%</small></strong></span></div><div><span class="legend-dot male"></span><span>Male<strong>596 <small>47.8%</small></strong></span></div></div></div><a class="population-link" href="#reports">View community report <i data-lucide="arrow-right" aria-hidden="true"></i></a></section>
                    </div>
                    <div class="workspace-lower">
                        <section class="requests-section" aria-labelledby="requests-heading"><div class="workspace-section-heading"><div><h2 id="requests-heading">Recent certificate requests</h2><p>A quick look at your latest transactions</p></div><a class="workspace-text-link" href="#certificates">View all <i data-lucide="arrow-right" aria-hidden="true"></i></a></div><div class="request-toolbar"><label class="workspace-search"><i data-lucide="search" aria-hidden="true"></i><input type="search" id="request-search" placeholder="Search name or reference..." aria-label="Search recent requests"></label><label class="period-select"><span class="sr-only">Request status</span><select id="request-status"><option value="all">All statuses</option><option>Pending</option><option>Issued</option><option>Processing</option></select><i data-lucide="chevron-down" aria-hidden="true"></i></label></div><div class="table-scroll"><table class="workspace-table"><thead><tr><th>Resident</th><th>Document</th><th>Status</th><th>Date</th><th><span class="sr-only">Details</span></th></tr></thead><tbody id="recent-requests"></tbody></table></div><div class="table-footer"><span id="request-summary">Showing 5 recent requests</span><span>Sample transactions</span></div></section>
                        <section class="activity-section" aria-labelledby="activity-heading"><div class="workspace-section-heading"><div><h2 id="activity-heading">Recent activity</h2><p>Across your barangay workspace</p></div><span class="activity-today">Today</span></div><ol class="activity-timeline"><li><span class="timeline-icon green"><i data-lucide="file-check-2" aria-hidden="true"></i></span><div><strong>Certificate issued</strong><p>Barangay clearance for Maria Santos</p><small>10:42 AM &middot; Certificates</small></div></li><li><span class="timeline-icon blue"><i data-lucide="user-round-plus" aria-hidden="true"></i></span><div><strong>New resident registered</strong><p>Carlo Reyes added to Purok 3</p><small>10:15 AM &middot; Residents</small></div></li><li><span class="timeline-icon gold"><i data-lucide="house" aria-hidden="true"></i></span><div><strong>Household updated</strong><p>Household HH-0326 details updated</p><small>9:38 AM &middot; Households</small></div></li><li><span class="timeline-icon rose"><i data-lucide="notebook-pen" aria-hidden="true"></i></span><div><strong>Hearing scheduled</strong><p>Follow-up for case BL-2026-014</p><small>9:10 AM &middot; Blotter records</small></div></li></ol><a href="#blotter" class="upcoming-hearing"><i data-lucide="calendar-clock" aria-hidden="true"></i><span><strong>Upcoming hearing</strong><small>Sep 21, 2026 &middot; 9:00 AM</small></span><i data-lucide="arrow-up-right" aria-hidden="true"></i></a></section>
                    </div>
                </div>

                <section id="records-view" hidden aria-labelledby="records-heading"><div class="records-heading-row"><div><h2 id="records-heading">Resident directory</h2><p id="records-description">Sample records in your barangay workspace.</p></div><button type="button" class="button button-outline" id="export-records"><i data-lucide="download" aria-hidden="true"></i> Export CSV</button></div><div class="request-toolbar"><label class="workspace-search"><i data-lucide="search" aria-hidden="true"></i><input type="search" id="records-search" placeholder="Search records..." aria-label="Search records"></label><span class="record-count" id="records-count"></span></div><div class="table-scroll"><table class="workspace-table"><thead id="records-head"></thead><tbody id="records-body"></tbody></table></div><div class="records-empty" id="records-empty" hidden><i data-lucide="search-x" aria-hidden="true"></i><h3>No matching records</h3><p>Try a different name, reference, or keyword.</p></div><div class="table-footer"><span>Sample records only</span><span>No live barangay data</span></div></section>
                <section id="reports-view" hidden aria-labelledby="reports-heading"><div class="records-heading-row"><div><h2 id="reports-heading">Community reports</h2><p>A snapshot of the sample barangay dataset.</p></div><button type="button" class="button button-outline" id="export-report"><i data-lucide="download" aria-hidden="true"></i> Export summary</button></div><div class="report-metrics"><div><span>Registered residents</span><strong>1,248</strong></div><div><span>Active households</span><strong>326</strong></div><div><span>Average household size</span><strong>3.8</strong></div></div><h3 class="report-subheading">Resident distribution by purok</h3><div id="purok-report"></div><p class="report-note">Illustrative totals for the demo workspace. Exports contain sample data.</p></section>
                <footer class="workspace-footer"><span>&copy; {{ date('Y') }} Barangay Information System</span><span><i data-lucide="hand-heart" aria-hidden="true"></i> Serving our community, together.</span></footer>
            </main>
        </div>
        <dialog id="workspace-dialog" aria-labelledby="workspace-dialog-title"><div class="dialog-top"><span class="eyebrow">BARANGAY WORKSPACE</span><button type="button" class="icon-button" data-close-workspace-dialog title="Close" aria-label="Close dialog"><i data-lucide="x" aria-hidden="true"></i></button></div><h2 id="workspace-dialog-title"></h2><div id="workspace-dialog-content"></div><button class="button button-primary" type="button" data-close-workspace-dialog>Done <i data-lucide="check" aria-hidden="true"></i></button></dialog>
        <dialog id="resident-dialog" aria-labelledby="resident-dialog-title"><div class="dialog-top"><span class="eyebrow">RESIDENT DIRECTORY</span><button type="button" class="icon-button" data-close-resident-dialog title="Close" aria-label="Close resident form"><i data-lucide="x" aria-hidden="true"></i></button></div><h2 id="resident-dialog-title">Add a resident</h2><p class="form-note">Demo entry only. Changes reset when this page is reloaded.</p><form id="resident-form"><div class="form-grid"><label>First name<input name="firstName" autocomplete="off" maxlength="60" required></label><label>Last name<input name="lastName" autocomplete="off" maxlength="60" required></label><label>Purok<select name="purok" required><option value="">Select purok</option>@for ($purok = 1; $purok <= 6; $purok++)<option>Purok {{ $purok }}</option>@endfor</select></label><label>Gender<select name="gender" required><option value="">Select gender</option><option>Female</option><option>Male</option><option>Prefer not to say</option></select></label></div><div class="form-actions"><button class="button button-outline" type="button" data-close-resident-dialog>Cancel</button><button class="button button-primary" type="submit"><i data-lucide="plus" aria-hidden="true"></i> Add demo resident</button></div></form></dialog>
        <div class="workspace-toast" id="workspace-toast" role="status" hidden></div>
    </body>
</html>
